### ISSUE TITLE
Adding datetime Skill [J.A.R.V.I.S AI Assistant (Python)]

### ISSUE THREAD

**Issue by siddeshshewde** [siddeshshewde/Projects#4]

**Comment by iriyagupta** [comment]
@siddeshshewde hi ! Taking up this issue

**Comment by anonymous-sidhax** [comment]
@siddeshshewde Can I please try this. I'm a beginner so adding datetime would be a good task for me.
@iriyagupta could you please take up other complex tasks?

**Comment by siddeshshewde** [comment]
Hi, @anonymous-sidhax : you can try out the temperate function which should be pretty straight forward as well. Please create a new issue for this.

**Comment by iriyagupta** [comment]
@siddeshshewde I have created the datetime file, shall I enable the calling of the function from the basic_skills.py file as well.

**Comment by siddeshshewde** [comment]
Good idea. sure @iriyagupta

**Comment by iriyagupta** [comment]
@siddeshshewde Okay, I will give it a try as well. Meanwhile, I will create the first pull request about the date-time file, if there are any suggestions, do let me know.

**Comment by siddeshshewde** [comment]
@iriyagupta : have commented on the PR. Let me know what do you think is best
