### ISSUE TITLE
Top Finance News Articles from CNBC [Telegram Bot (Python)]

### ISSUE THREAD

**Issue by siddeshshewde** [siddeshshewde/Projects#6]

**Comment by shivanshsinghal107** [comment]
So will you be running the bot for trial on telegram after my PR for testing the functionalities or should I?

**Comment by shivanshsinghal107** [comment]
And should I remove all commented part of the code or leave it as it is. Also is there any use of the command & function for 'Hi'? I am asking for all this just to make the code more clean.

**Comment by siddeshshewde** [comment]
I was actually playing around with requests module to figure out a good way to handle errors. We can remove the commented part and Hi function as both of them were used for testing purposes.

**Comment by shivanshsinghal107** [comment]
I have implemented the functionalities from my side, let me know how are they running on telegram.
